[package]
name = "mastodon-wsj-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = { version = "2.0.*" }
reqwest = { version = "0.11.*" }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.23" }
redis = { version = "0.22.*" }

mongodb = "2.3.1"
bson = { version ="2", features = ["chrono-0_4"] }
serde = "1"

oauth2 = "4.3.*"
log = "0.4"
log4rs = "1"
serde_yaml = "0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }